apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
spec:
  clusterIP: None
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  - name: sentinel
    port: 26379
    protocol: TCP
    targetPort: 26379
  selector:
    app: redis
  type: ClusterIP
status:
  loadBalancer: {}
